Practica/Models/Formulario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace Practica.Models
{
    public class Formulario
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "El campo nombre es requerido")]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "El campo apellido paterno es requerido")]
        [Display(Name = "Apellido Paterno")]
        public string apellidoP { get; set; }

        [Required(ErrorMessage = "El campo apellido materno es requerido")]
        [Display(Name = "Apellido Materno")]
        public string apellidoM { get; set; }

        [Required(ErrorMessage = "El campo usuario es requerido")]
        [Display(Name = "Usuario")]
        public string usuario { get; set; }

        [Required(ErrorMessage = "El campo contraseña es requerido")]
        [Display(Name = "Contraseña")]
        public string contrasena { get; set; }

        [Required(ErrorMessage = "El campo telefono es requerido")]
        [Display(Name = "Telefono")]
        public int telefono { get; set; }

        [Required(ErrorMessage = "El campo dirección es requerido")]
        [Display(Name = "Dirección")]
        public string direccion { get; set; }
    

        





       
        
    }
}

Practica/Controllers/FormulariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Practica.Models;

namespace Practica.Controllers
{
    public class FormulariosController : Controller
    {
        public readonly PracticaContext _context;
        public IConfiguration Configuration { get; }

        public FormulariosController(PracticaContext context, IConfiguration configuration)
        {
            _context = context;
            Configuration = configuration;
        }

        public async Task<IActionResult> Index(string FormularioBusqueda, string searchString)
        {
           
            IQueryable<string> genreQuery = from b in _context.Formulario
                                     
                                            orderby b.direccion
                                            select b.direccion;
            var busqueda = from b in _context.Formulario
                         select b;

            if (!String.IsNullOrEmpty(searchString))
            {
                busqueda = busqueda.Where(s => s.nombre.Contains(searchString));
            }
            if (!string.IsNullOrEmpty(FormularioBusqueda))
            {
                busqueda = busqueda.Where(x => x.direccion == FormularioBusqueda);
            }
            var formulariobusq = new FormularioGenreViewModel
            {
                Busqueda = new SelectList(await genreQuery.Distinct().ToListAsync()),
                Formulario = await busqueda.ToListAsync()
            };

            return View(formulariobusq);
        }
      



        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: aceptar  " + searchString;
        }

        // GET: Formularios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var formulario = await _context.Formulario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (formulario == null)
            {
                return NotFound();
            }

            return View(formulario);
        }
        // GET: Formularios/Create
        public IActionResult Create()
        {
            return View();
        }

        // GET: Formularios/Create
        [HttpPost]
        public IActionResult Create(Formulario formulario)
        {
            if (ModelState.IsValid)
            {
                
                string connectionString = Configuration["ConnectionStrings:PracticaContext"];
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    string sql = $"Insert Into Formulario(nombre, apellidoP, apellidoM, usuario, contrasena, telefono, direccion) Values ('{formulario.nombre}', '{formulario.apellidoP}','{formulario.apellidoM}','{formulario.usuario}', '{formulario.contrasena}', '{formulario.telefono}', '{formulario.direccion}' )";
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.CommandType = CommandType.Text;
                        connection.Open();
                        command.ExecuteNonQuery();
                        connection.Close();
                        connection.Dispose();

                    }
                    return RedirectToAction("Index");
                }

            }
            else
                return View();
        }

    

  

    // GET: Formularios/Edit
    public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var formulario = await _context.Formulario.FindAsync(id);
            if (formulario == null)
            {
                return NotFound();
            }
            return View(formulario);
        }

        // POST: Formularios/Edit

        [HttpPost]
        public IActionResult Edit(Formulario formulario)
        {
            if (ModelState.IsValid)
            {
                string connectionString = Configuration["ConnectionStrings:PracticaContext"];
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    string sql = $"UPDATE Formulario SET nombre='{formulario.nombre}', apellidoP ='{formulario.apellidoP}', apellidoM ='{formulario.apellidoM}', usuario ='{formulario.usuario}', contrasena ='{formulario.contrasena}', telefono ='{formulario.telefono}', direccion ='{formulario.direccion}' WHERE Id='{formulario.Id}'";

                  
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.CommandType = CommandType.Text;
                        connection.Open();
                        command.ExecuteNonQuery();
                        connection.Close();
                        connection.Dispose();

                    }
                    return RedirectToAction("Index");
                }

            }
            else
                return View();
        }
                // GET: Formularios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var formulario = await _context.Formulario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (formulario == null)
            {
                return NotFound();
            }

            return View(formulario);
        }

        // POST: Formularios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var formulario = await _context.Formulario.FindAsync(id);
            _context.Formulario.Remove(formulario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FormularioExists(int id)
        {
            return _context.Formulario.Any(e => e.Id == id);
        }



        // GET: Formulario/ContactPDF
        public async Task<IActionResult> ContactPDF()
        {
            
            return new Rotativa.AspNetCore.ViewAsPdf("ContactPDF", await _context.Formulario.ToListAsync())
            {
                // Establece el número de página.
                CustomSwitches = "--page-offset 0 --footer-center [page] --footer-font-size 12"
            };
        }


    }
}

Practica/Views/Formularios/ContactPDF.cshtml
@model IEnumerable<Practica.Models.Formulario>

    @{
    ViewData["Title"] = "ContactPDF";
    }
    @{
    Layout = null;
    }

    
    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>ContactosPDF</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </head>
    <body>
        <table>
            <thead>
                <tr>
                    <th>
                        <img src="~/images/logopdf.png" />
                    </th>
                    <th>
                        <h2 style="margin-left: 150px;  color:#083E73";>Lista de usuarios</h2>
                    </th>
                </tr>
            </thead>
        </table>
       
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.apellidoP)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.apellidoM)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.usuario)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.contrasena)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.telefono)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.direccion)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.apellidoP)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.apellidoM)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.usuario)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.contrasena)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.telefono)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.direccion)
                    </td>
                   
                </tr>
}
            </tbody>
        </table>
        </body>
</html>

Practica/Views/Formularios/Create.cshtml
@model Practica.Models.Formulario

@{
    ViewData["Title"] = "Create";
}

<h2>Nuevo usuario</h2>

<h4>Datos solicitados </h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellidoP" class="control-label"></label>
                <input asp-for="apellidoP" class="form-control" />
                <span asp-validation-for="apellidoP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellidoM" class="control-label"></label>
                <input asp-for="apellidoM" class="form-control" />
                <span asp-validation-for="apellidoM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="usuario" class="control-label"></label>
                <input asp-for="usuario" class="form-control" />
                <span asp-validation-for="usuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="contrasena" class="control-label" ></label>
                <input asp-for="contrasena" type="password" class="form-control" />
                <span asp-validation-for="contrasena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefono" class="control-label"></label>
                <input asp-for="telefono" class="form-control" />
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="direccion" class="control-label"></label>
                <input asp-for="direccion" class="form-control"  />
                <span asp-validation-for="direccion" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Crear usuario" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" >Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Practica/Views/Formularios/Delete.cshtml
@model Practica.Models.Formulario

<h3>¿Estas seguro que deseas eliminar este usuario?</h3>
<div>
    <h4>Formulario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.apellidoP)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.apellidoP)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.apellidoM)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.apellidoM)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.usuario)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.usuario)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.contrasena)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.contrasena)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.direccion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.direccion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver a la lista</a>
    </form>
</div>

Practica/Views/Formularios/Details.cshtml
@model Practica.Models.Formulario

@{
    ViewData["Title"] = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>Formulario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.apellidoP)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.apellidoP)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.apellidoM)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.apellidoM)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.usuario)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.usuario)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.contrasena)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.contrasena)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.direccion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.direccion)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Modificar</a> |
    <a asp-action="Index">Volver a la lista</a>
</div>

Practica/Views/Formularios/Edit.cshtml
@model Practica.Models.Formulario

@{
    ViewData["Title"] = "Edit";
}

<h2>Modificar</h2>

<h4>Datos del usuario que se desea modificar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellidoP" class="control-label"></label>
                <input asp-for="apellidoP" class="form-control" />
                <span asp-validation-for="apellidoP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellidoM" class="control-label"></label>
                <input asp-for="apellidoM" class="form-control" />
                <span asp-validation-for="apellidoM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="usuario" class="control-label"></label>
                <input asp-for="usuario" class="form-control" />
                <span asp-validation-for="usuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="contrasena" class="control-label"></label>
                <input asp-for="contrasena" class="form-control" />
                <span asp-validation-for="contrasena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefono" class="control-label"></label>
                <input asp-for="telefono" class="form-control" />
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="direccion" class="control-label"></label>
                <input asp-for="direccion" class="form-control" />
                <span asp-validation-for="direccion" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Modificar" class="btn btn-warning" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Practica/Views/Formularios/Index.cshtml
@model Practica.Models.FormularioGenreViewModel

@{
    ViewData["Title"] = "Registro";
}

<h1 style="color:#075D99; margin-left: 400px;">Lista de usuarios </h1>

<p>
    <a asp-action="Create" style="color:#075D99; margin-left: 890px;">Registrar nuevo usuario</a>
</p>
<form asp-controller="Formularios" asp-action="Index" method="get">
    <div class="list-group-item disabled" aria-disabled="true" style="margin-left: 580px;">
  <center><h4 >Buscar</h4></center><br />
                                  <div class="text-decoration-none">
                                      <label class="text-decoration-none">Nombre</label>  <input type="text" asp-for="SearchString"  class="input-group-prepend"/>

                                      <select asp-for="FormularioBusqueda" asp-items="Model.Busqueda" class="btn btn-secondary">
                                          <option value="">---Selecciona todos---</option>
                                      </select>

                                      <input type="submit" value="Aceptar" class="btn btn-info" />
                                  </div>
        </div>
</form>
<br />

<table class="table table-striped">
    <thead>
        <tr style="color:#30365B;">
            <th>
                
                @Html.DisplayNameFor(model => model.Formulario[0].nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Formulario[0].apellidoP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Formulario[0].apellidoM)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Formulario[0].usuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Formulario[0].contrasena)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Formulario[0].telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Formulario[0].direccion)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
       
            @foreach (var item in Model.Formulario)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.apellidoP)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.apellidoM)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.usuario)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.contrasena)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.telefono)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.direccion)
                    </td>

                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-default">Modificar</a> |
                        <a asp-action="Details" asp-route-id="@item.Id"  class="btn btn-default" >Detalle</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Eliminar</a>|

                    </td>
                </tr>
            }
    </tbody>
</table>
<div class="list-group">
   
    <ul class="list-unstyled list-inline text-center">
        
        <li class="list-group-item list-group-item-action list-group-item-primary">
            <a href="Formularios/ContactPDF"  target="_blank" class="btn btn-success">Generar PDF </a>
        </li>
    </ul>
   
</div>